name: subtitle
description: Library for dealing with subtitle/caption formats.
version: 0.1.0-beta.1
homepage: https://github.com/dsc-uob/subtitle

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  path: ">=1.8.0 <1.9.0"
  http: ">=0.13.3 <0.14.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
